NDefines.NGame.DAYS_BEHIND_PAUSE = 365 -- Vanilla 25
NDefines.NGame.DAYS_BEHIND_LOWER_SPEED = 365	--Vanilla 10				   

NDefines.NDiplomacy.CHANGE_RIVAL_YEARS = 5
NDefines.NDiplomacy.DISHONORABLE_PEACE_MONTHS = 0
NDefines.NDiplomacy.DISHONORABLE_PEACE_WARSCORE = 0
NDefines.NDiplomacy.DEFENDER_OF_FAITH_TRUST_LOSS = 0
NDefines.NDiplomacy.CRUSADE_TIMEOUT_YEARS = 15
NDefines.NDiplomacy.ANNUL_TREATIES_YEARS = 20
NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200 --Vanilla -25
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 12 --Vanilla 60
NDefines.NDiplomacy.ABANDON_UNION_PRESTIGE = 0 --Vanilla -25
NDefines.NDiplomacy.RIVAL_PEACE_COST_REDUCTION = -0.20 --Vanilla -0.33
NDefines.NDiplomacy.EMPEROR_VOTE_DAYS = 10 --Vanilla 60
NDefines.NDiplomacy.DIPLOMAT_SPEED = 50 --Vanilla 20
NDefines.NDiplomacy.STABHIT_FOR_BREAKING_ALLIANCE_IN_WAR = 5
NDefines.NDiplomacy.INTEGRATE_UNION_MIN_YEARS = 25
NDefines.NDiplomacy.INTEGRATE_VASSAL_MIN_YEARS = 10
NDefines.NDiplomacy.DAYS_TO_DECLARE_WAR = 5
NDefines.NDiplomacy.GREAT_PROJECT_WARSCORE_COST_MODIFIER = 0.25
NDefines.NDiplomacy.HRE_PRINCE_AUTHORITY_THRESHOLD = 10
NDefines.NDiplomacy.FABRICATE_CLAIM_COST = 10
NDefines.NDiplomacy.FABRICATE_CLAIM_COST_MODIFIER_PER_CLAIM = 0.25
NDefines.NDiplomacy.CLAIM_STATE_MODIFIER = 0.25
NDefines.NDiplomacy.LEAVING_GREAT_POWER_YEARS = 1
NDefines.NDiplomacy.IMPERIAL_CITY_IA = 0.01
NDefines.NDiplomacy.FORCE_BREAK_ALLIANCE_TRUCE_YEARS = 0
NDefines.NDiplomacy.UNCONDITIONAL_SURRENDER_MIN_MONTHS = 1	
NDefines.NDiplomacy.TRADE_LEAGUE_BREAK_OPINION = -200
NDefines.NDiplomacy.GREAT_POWER_SUBJECT_CONTRIBUTION = 0.75
NDefines.NDiplomacy.AUTONOMY_WARSCORE_COST_MODIFIER = 0.5
NDefines.NDiplomacy.PEACE_COST_GOLD_STEP = 4
NDefines.NDiplomacy.PEACE_COST_WAR_REPARATIONS = 5
NDefines.NDiplomacy.PEACE_COST_HUMILIATE_RIVAL = 30
NDefines.NDiplomacy.PEACE_COST_DEMAND_NON_OCCUPIED_PROVINCE_MULT = 1
NDefines.NDiplomacy.PEACE_COST_DEMAND_PROVINCE = 1					-- Demand a province (scales by province wealth, also used for annex)
NDefines.NDiplomacy.PEACE_COST_CONCEDE_PROVINCE = 1000				-- Demand colonial area province concession.
NDefines.NDiplomacy.PEACE_COST_ANNUL = 5
NDefines.NDiplomacy.REFUSED_CALL_FROM_TRIBUTARY_MANDATE_LOSS = 0
NDefines.NDiplomacy.CELESTIAL_EMPIRE_MANDATE_PER_5_LOANS = -0.36
NDefines.NDiplomacy.CELESTIAL_EMPIRE_REFORM_MIN_VALUE = 70
NDefines.NDiplomacy.CHANGE_COLONIAL_TYPE_COST = 0

NDefines.NCountry.ABANDON_IDEAGROUP_REFUND = 0.25
NDefines.NCountry.ABDICATE_LEGITIMACY_THRESHOLD = 0
NDefines.NCountry.ABDICATE_AGE_THRESHOLD = 30
NDefines.NCountry.ABDICATE_RULING_LENGTH_THRESHOLD = 10
NDefines.NCountry.ABDICATE_LEGITIMACY_HIT = 0
NDefines.NCountry.ABDICATE_PRESTIGE_HIT = -25
NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -25
NDefines.NCountry.NEW_HEIR_PRESTIGE_HIT = -25
NDefines.NCountry.NEW_HEIR_LEGITIMACY_HIT = -25
NDefines.NCountry.NEW_HEIR_LEGITIMACY_THRESHOLD = 25		-- per dev
NDefines.NCountry.MIN_PRESTIGE_FOR_GOV_RANK_2 = 1			-- Required prestige to to upgrade to government rank 2
NDefines.NCountry.MIN_PRESTIGE_FOR_GOV_RANK_3 = 25
NDefines.NCountry.MAX_IDEA_GROUPS_FROM_SAME_CATEGORY = 0.4
NDefines.NCountry.PIETY_PERCENTAGE_AT_NEW_RULER = 1
NDefines.NCountry.PIETY_INCREASE_AT_GOOD_WAR = 0
NDefines.NCountry.PIETY_DECREASE_AT_BAD_WAR = 0
NDefines.NCountry.HORDE_UNITY_PER_LOOT = 0
NDefines.NCountry.MONARCH_DEATH_LEADER_STABILITY_PENALTY = 0
NDefines.NCountry.NAT_FOCUS_YEARS = 0
NDefines.NCountry.NAT_FOCUS_YEARS_RANK = 0
NDefines.NCountry.MAX_TOLERANCE_HERETIC = 5
NDefines.NCountry.MAX_TOLERANCE_HEATHEN = 5
NDefines.NCountry.PS_ASSAULT = 0
NDefines.NCountry.PS_ARTILLERY_BARRAGE = 25
NDefines.NCountry.PS_NAVAL_BARRAGE = 15
NDefines.NCountry.PS_PROMOTE_MERCANTILISM = 75
NDefines.NCountry.PS_MOVE_CAPITAL_EXTRA = 20
NDefines.NCountry.PS_MOVE_CAPITAL_DISTANCE = 0
NDefines.NCountry.PS_MOVE_CAPITAL_DISTANCE_CAP = 0
NDefines.NCountry.PS_MOVE_TRADE_PORT = 50
NDefines.NCountry.PS_REPLACE_RIVAL = 0
NDefines.NCountry.PS_CHANGE_CULTURE = 5
NDefines.NCountry.MONTHS_TO_CHANGE_CULTURE = 5
NDefines.NCountry.PS_ADD_ACCEPTED_CULTURE = 25
NDefines.NCountry.CULTURE_MIN_DEVELOPMENT_TO_PROMOTE = 5
NDefines.NCountry.YEARS_OF_NATIONALISM = 20
NDefines.NCountry.PS_REMOVE_ACCEPTED_CULTURE = 0
NDefines.NCountry.PS_ATTACK_NATIVES = 1
NDefines.NCountry.PS_HARSH_TREATMENT_COST = 50
NDefines.NCountry.PS_IMPROVE_PROVINCE_CAPITAL_DISCOUNT = 0.005
NDefines.NCountry.STRENGTHEN_GOVERNMENT_LEGITIMACY = 20
NDefines.NCountry.PROVOKE_REVOLT_MIN_PROGRESS = 30.0
NDefines.NCountry.CALL_ALLY_DECLINE_PRESTIGE_PENALTY = 0
NDefines.NCountry.BREAK_VASSAL_PRESTIGE_PENALTY = 0
NDefines.NCountry.CORE_LOSE_PRESTIGE = 0
NDefines.NCountry.CORE_HAD_PERMANENT_CLAIM = 0.15
NDefines.NCountry.ABANDON_CORE_PRESTIGE = 0
NDefines.NCountry.REGULAR_COLONY_GROWTH = 60
NDefines.NCountry.COLONIAL_CLAIM_BONUS = 20
NDefines.NCountry.COLONIAL_CLAIM_VIOLATION = 0
NDefines.NCountry.COLONY_VIOLAION_PAPAL_INFLUENCE_COST  = 0
NDefines.NCountry.LIBERTY_DESIRE_HISTORICAL_RIVAL = 0
NDefines.NCountry.NORMAL_ELECTION_CYCLE = 5
NDefines.NCountry.PROMOTE_INVESTMENTS_TRADEPOWER = 0
NDefines.NCountry.PROMOTE_INVESTMENTS_INFLATION = 0
NDefines.NCountry.INNOVATIVENESS_AHEAD_OF_TIME_BONUS = 0.005
NDefines.NCountry.INNOVATIVENESS_FIRST_REACHED_TECH_LEVEL = 4.0  -- Innovativeness bonus to first country (or countries) to reach a certain tech level.
NDefines.NCountry.INNOVATIVENESS_FIRST_PICKED_IDEA = 2.0			-- Innovativeness bonus to first country (or countries) to pick an idea.	
NDefines.NCountry.MINIMUM_POLICY_TIME = 0.1
NDefines.NCountry.ESTATE_MIN_DISTRIBUTED_CROWNLAND = 30.5
NDefines.NCountry.ESTATE_DEFAULT_LOYALTY = 40
NDefines.NCountry.LAGGINGTECH_CORRUPTION = 0.25					-- Corruption increase/year. Multiplied by (highest - lowest) tech level
NDefines.NCountry.LAGGINGTECH_CORRUPTION_MAX = 1				-- Max increase/year
NDefines.NCountry.NATIVE_UPRISING_COOLDOWN_MONTHS = 120
NDefines.NCountry.NATIVE_UPRISING_CHANCE_PER_AGGRESSIVENESS = -1
NDefines.NCountry.INNOVATIVENESS_AHEAD_OF_TIME_BONUS = 0
NDefines.NCountry.MONARCH_MIN_SKILL = 1
NDefines.NCountry.MAX_PROVINCES_FOR_FREE_CITY = 8
NDefines.NEconomy.MAX_BUILDING_SLOTS = 18
NDefines.NEconomy.EDICTS_DURATION_MONTHS = 1
NDefines.NEconomy.DEBASE_MAX_CORRUPTION = 10
NDefines.NEconomy.CARAVAN_FACTOR = 3.0
NDefines.NEconomy.CARAVAN_POWER_MAX = 30
NDefines.NEconomy.COT_DOWNGRADE_PRESTIGE_COST = 0
NDefines.NEconomy.GOLD_MINE_DEPLETION_THRESHOLD = 10				-- Gold mines above production level or above can be depleted
NDefines.NEconomy.GOLD_MINE_DEPLETION_CHANCE = 0.05
NDefines.NEconomy.TRADE_PROPAGATE_DIVIDER = 20
NDefines.NEconomy.HEAVY_SHIP_MAINT_FACTOR = 0.07		

NDefines.NMilitary.MIN_MONTHLY_MANPOWER = 0.2						-- 100 men/month is minimum
NDefines.NMilitary.MIN_MONTHLY_SAILORS = 10	
NDefines.NMilitary.FORTRESS_COST = 0.25
NDefines.NMilitary.ARMY_DRILL_YEARLY_GAIN = 33.3
NDefines.NMilitary.ARMY_DRILL_SKILL_MONTHS = 60
NDefines.NMilitary.GARRISON_SIZE = 3000	
NDefines.NMilitary.SIEGE_FORCE_NEEDED_MULTIPLIER =  0.334			-- x times garrison to be able to siege.
NDefines.NMilitary.MAX_BREACH = 1
NDefines.NMilitary.SUPPLYLIMIT_BASE_MULTIPLIER = 8.0
NDefines.NMilitary.DEFAULT_WARGOAL_TICKINGWARSCORE_BONUS = 1.67
NDefines.NMilitary.WARGOAL_MAX_BONUS = 30
NDefines.NMilitary.WARSCORE_MAX_FROM_BATTLES = 50
NDefines.NMilitary.LEADER_MIN_PIPS = 2
NDefines.NMilitary.SUPPLY_DEPOT_MIL_COST = 5 --Vanilla 20
NDefines.NMilitary.BACK_LINE_MORALE_DAMAGE_TAKEN_MODIFIER = 0.0 -- Vanilla 0.4
NDefines.NMilitary.BACK_LINE_STRENGTH_DAMAGE_TAKEN_MODIFIER = 0.0
NDefines.NMilitary.BACK_LINE_REINFORCE_SPEED = 40
NDefines.NMilitary.TRANSPORT_COST = 1 --Vanilla 10
NDefines.NMilitary.TRANSPORT_TIME = 60 --Vanilla 365
NDefines.NGovernment.SELECT_HEIR_FROM_HAREM_AT_MONARCH_AGE = 20
NDefines.NGovernment.GOVERNMENT_REFORM_CHANGE_PROGRESS_COST = 10

















